First Request
vanyakot/LogSystem pull request #2
Opened 2020-05-15 20:01 UTC by vanyakot

2020-05-16 09:12 UTC, maksimboch requested changes

2020-05-16 09:12 UTC, maksimboch commented on Log_system/Data/Model/LogData.cs
> +﻿using System;
Лишние using. Студия сама их создает при генерации класса.
Проверь warning-и, обычно она пишет что using можно удалить.

В других классах тоже посмотри, в каждом не буду писать одинаковый комментарий.

2020-05-16 09:12 UTC, maksimboch commented on Log_system/Data/Receive/Handler.cs
> +    public class Handler
Нужно более осмысленное название. Handler - это чистая абстракция. Ты должен из названия понимать что делает твой класс

2020-05-16 09:12 UTC, maksimboch commented on Log_system/Data/Receive/Handler.cs
> +using System.Text.Json;
У меня ругается на System.Text.Json. У тебя точно с ним работает?

2020-05-16 09:12 UTC, maksimboch commented on Log_system/Data/Receive/Handler.cs
> +        private IHttpClient _client;
Все, что инжектируем и создаем в конструкторе принято помечать как readonly

2020-05-16 09:12 UTC, maksimboch commented on Log_system/Log_system.csproj
> +    <Folder Include="Controllers\" />
Знаю, что скоро здесь появится контроллер, но в целом не стоит оставлять пустые namespace в проекте.

2020-05-16 09:12 UTC, maksimboch commented on Log_system/Log_system.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
Выглядит как лишняя зависимость, созданная из шаблона проекта. Проверь нужна ли она и удали если нет.

2020-05-16 09:12 UTC, maksimboch commented on Log_system/Properties/launchSettings.json
> +      "applicationUrl": "https://localhost:5001;http://localhost:5000"
Почему у application 2 урла? Это ты добавил?

2020-05-16 09:12 UTC, maksimboch commented on Log_system/Properties/launchSettings.json
> +      "launchUrl": "api/values",
По идее если убрать эту строчку то перестанет при запуске открывать страницу. Проверь.

2020-05-16 09:12 UTC, maksimboch commented on Log_system/Services/HttpClient/HttpClient.cs
> +    public class HttpClient:IHttpClient
HttpClient : IHttpClient
У нас для читаемости принято отбивать интерфейсы и тд пробелами.

2020-05-16 09:12 UTC, maksimboch commented on Log_system/Services/HttpClient/HttpClient.cs
> +        public async Task SendGetRequest()
Тут я бы тоже отбил новой строкой.

2020-05-16 09:12 UTC, maksimboch commented on Log_system/Services/HttpClient/HttpClient.cs
> +            _source = config["DataUrl"];
Секцию лучше получаеть через Configuration.GetSection().
По именованию тоже лучше назвать configuration.

2020-05-16 09:12 UTC, maksimboch commented on Log_system/Services/HttpClient/HttpClient.cs
> +            WebRequest request = WebRequest.Create(_source);
Я бы переписал на получение HttpResponseMessage. У больше заточен под получение контента

2020-05-16 09:12 UTC, maksimboch commented on Log_system/Data/Receive/Handler.cs
> +            _client.SendGetRequest();
Метод у тебя async. Но используешь ты его синхронно. Почитай про async\await

2020-05-16 09:12 UTC, maksimboch commented on Log_system/Services/HttpClient/IHttpClient.cs
> +        string _response { get; set; }
Это лишнее в интерфейсе, тем более с геттером.

2020-05-16 09:12 UTC, maksimboch commented on Log_system/appsettings.json
> +  "LogDB":  "Data Source=DESKTOP-11J4L5C;Initial Catalog=LogData;Integrated Security=True;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False"
Для connectionStrings обычно используют отдельную секцию и получают через Configuration.GetConnectionString()
https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.configurationextensions.getconnectionstring?view=dotnet-plat-ext-3.1

2020-05-16 09:12 UTC, maksimboch commented on Log_system/Startup.cs
> +            RecurringJob.AddOrUpdate<Handler>(h => h.ReceiveInfo(), Cron.Minutely);
Я бы вынес создание job у hangire в отдельный метод CreateHangfireJobs()

2020-05-16 09:12 UTC, maksimboch commented on Log_system/Startup.cs
> +            services.AddTransient<IHttpClient, HttpClient>();
Добавление сервисов тоже предлагаю вытащить в отдельный метод, а лучше даже класс.
Представь, что у тебя не 1, а скажем 50 сервисов. Это нормально захламит Startup файл

2020-05-16 09:12 UTC, maksimboch commented on Log_system/Startup.cs
> +            services.AddHangfire(x => x.UseSqlServerStorage(@"Data Source=DESKTOP-11J4L5C;Initial Catalog=Query;Integrated Security=True;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=R
ConnectionString надо вынести в конфиг.

2020-05-16 09:12 UTC, maksimboch commented on Log_system/Services/Repositories/LogRepository.cs
> +            connectionString = config["LogData"];
Аналогично, используй GetConnectionString когда будешь реализовывать репозиторий.

2020-05-16 09:12 UTC, maksimboch commented on Log_system/Data/Receive/Handler.cs
> +namespace Log_system.Data.Receive
Ты выделил два крупных namespace Data и Services. И это точно не Data :)

2020-05-16 14:19 UTC, vanyakot commented on Log_system/Data/Receive/Handler.cs
> +using System.Text.Json;
Да , работает , нужно скачать доп пакет , чтобы работало , мне студия изначально предлагала использовать using Newtonsoft.Json , но при десериализации просит не string , а Newtonsoft.Json.JsonReader.

2020-05-16 16:36 UTC, vanyakot commented on Log_system/Data/Model/LogData.cs
> +﻿using System;
Удалил

2020-05-16 17:35 UTC, vanyakot commented on Log_system/Startup.cs
> +            services.AddHangfire(x => x.UseSqlServerStorage(@"Data Source=DESKTOP-11J4L5C;Initial Catalog=Query;Integrated Security=True;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=R
Вынес

2020-05-16 17:36 UTC, vanyakot commented on Log_system/Services/Repositories/LogRepository.cs
> +            connectionString = config["LogData"];
Изменил

2020-05-16 17:36 UTC, vanyakot commented on Log_system/Log_system.csproj
> +    <Folder Include="Controllers\" />
Убрал до реализации контроллера

2020-05-16 17:37 UTC, vanyakot commented on Log_system/Data/Receive/Handler.cs
> +        private IHttpClient _client;
Изменил на readonly

2020-05-16 21:41 UTC, vanyakot commented on Log_system/Properties/launchSettings.json
> +      "launchUrl": "api/values",
Убрал

2020-05-17 11:19 UTC, vanyakot commented on Log_system/Startup.cs
> +            RecurringJob.AddOrUpdate<Handler>(h => h.ReceiveInfo(), Cron.Minutely);
Вынес

2020-05-17 11:20 UTC, vanyakot commented on Log_system/Services/HttpClient/HttpClient.cs
> +            _source = config["DataUrl"];
Поправил

2020-05-17 11:21 UTC, vanyakot commented on Log_system/appsettings.json
> +  "LogDB":  "Data Source=DESKTOP-11J4L5C;Initial Catalog=LogData;Integrated Security=True;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False"
Поправил

2020-05-17 11:24 UTC, vanyakot commented on Log_system/Services/HttpClient/HttpClient.cs
> +    public class HttpClient:IHttpClient
Отбил

2020-05-17 11:29 UTC, vanyakot commented on Log_system/Services/HttpClient/HttpClient.cs
> +        public async Task SendGetRequest()
Отбил

2020-05-17 11:29 UTC, vanyakot commented on Log_system/Properties/launchSettings.json
> +      "applicationUrl": "https://localhost:5001;http://localhost:5000"
Нет , сразу было , оставил один

2020-05-17 11:35 UTC, vanyakot commented on Log_system/Services/HttpClient/HttpClient.cs
> +            WebRequest request = WebRequest.Create(_source);
Переписал

2020-05-17 11:49 UTC, vanyakot commented on Log_system/Services/HttpClient/IHttpClient.cs
> +        string _response { get; set; }
Убрал

2020-05-18 13:19 UTC, vanyakot commented on Log_system/Startup.cs
> +            services.AddTransient<IHttpClient, HttpClient>();
Исправлено

2020-05-18 13:20 UTC, vanyakot commented on Log_system/Data/Receive/Handler.cs
> +namespace Log_system.Data.Receive
Переместил в Services

2020-05-18 13:20 UTC, vanyakot commented on Log_system/Data/Receive/Handler.cs
> +            _client.SendGetRequest();
Переделал

2020-05-18 13:21 UTC, vanyakot commented on Log_system/Log_system.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
Убрал

2020-05-18 13:21 UTC, vanyakot commented on Log_system/Data/Receive/Handler.cs
> +    public class Handler
Переименовал

2020-05-19 05:55 UTC, maksimboch requested changes

2020-05-19 05:55 UTC, maksimboch commented on Log_system/Services/DataConverter/DataConverter.cs
> +            return JsonSerializer.Deserialize<T>(json);
У нас принято отбивать return новой строкой. 
![изображение](https://user-images.githubusercontent.com/65163033/82289233-00cc4380-99ad-11ea-8f2d-2b0fd1c35b91.png)

2020-05-19 05:55 UTC, maksimboch commented on Log_system/Services/DataConverter/DataConverter.cs
> +        public async Task<T> WebResponseToObj<T>()
Название метода обычно содержит в себе глагол, полноценно описывающий выполняемую им задачу.

2020-05-19 05:55 UTC, maksimboch commented on Log_system/Services/DataController/DataController.cs
> +           data = await _converter.WebResponseToObj<LogData>();
Что-то с отступами.

2020-05-19 05:55 UTC, maksimboch commented on Log_system/Services/DataController/DataController.cs
> +        private LogData data;
Не понимаю зачем ты создаешь приватные переменные в области класса, а не метода?

2020-05-19 05:55 UTC, maksimboch commented on Log_system/Services/DataConverter/DataConverter.cs
> +    public class DataConverter : IDataConverter
Я бы назвал этот класс DataClient, думаю можно это в звонке обсудить

2020-05-19 05:55 UTC, maksimboch commented on Log_system/Services/DataConverter/DataConverter.cs
> +        private string json;
Опять непонятная переменная за методом

2020-05-19 05:55 UTC, maksimboch commented on Log_system/Services/HttpClient/HttpClient.cs
> +            return await request.GetResponseAsync();
По форматированию не забывай смотреть перед пушем

2020-05-19 05:55 UTC, maksimboch commented on Log_system/Services/Repositories/LogRepository.cs
> +        private readonly string connectionString;
По именованию в классах. 
Приватные переменные _veryImportantVar. 
Константы VeryImportantVar.
Публичные поля VeryImportantVar.

2020-05-19 05:55 UTC, maksimboch commented on Log_system/Startup.cs
> +        private void ExtensionsServices(IServiceCollection services)
ExtensionService не подходит, тут скорее ConfigureServices

2020-05-19 05:55 UTC, maksimboch commented on Log_system/appsettings.json
> +  "DataUrl": "http://localhost:58297/log-system-data/get-log-system-data",
Эти данные в конфиге чисто твои. Хотелось бы чтобы они были в твоем персональном конфиге.

2020-05-19 16:43 UTC, vanyakot commented on Log_system/Startup.cs
> +        private void ExtensionsServices(IServiceCollection services)
Так не получится же назвать , назвал RegisterServices

2020-05-19 16:43 UTC, vanyakot commented on Log_system/Services/DataConverter/DataConverter.cs
> +    public class DataConverter : IDataConverter
Переименовал

2020-05-19 16:43 UTC, vanyakot commented on Log_system/Services/DataConverter/DataConverter.cs
> +            return JsonSerializer.Deserialize<T>(json);
Отбил

2020-05-19 16:44 UTC, vanyakot commented on Log_system/Services/DataConverter/DataConverter.cs
> +        public async Task<T> WebResponseToObj<T>()
Переименовал

2020-05-19 16:44 UTC, vanyakot commented on Log_system/Services/DataController/DataController.cs
> +           data = await _converter.WebResponseToObj<LogData>();
Поправил

2020-05-19 16:46 UTC, vanyakot commented on Log_system/Services/DataController/DataController.cs
> +        private LogData data;
Переместил

2020-05-19 16:47 UTC, vanyakot commented on Log_system/Services/DataConverter/DataConverter.cs
> +        private string json;
Переместил

2020-05-19 16:49 UTC, vanyakot commented on Log_system/Services/HttpClient/HttpClient.cs
> +            return await request.GetResponseAsync();
А где тут ошибка в форматировании ?

2020-05-19 16:51 UTC, vanyakot commented on Log_system/Services/Repositories/LogRepository.cs
> +        private readonly string connectionString;
Переименовал

2020-05-21 07:55 UTC, maksimboch approved these changes

2020-05-21 19:35 UTC, merged